name = "HilleYosida"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["HilleYosida"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "BochnerMinlos"
git = "https://github.com/mrdouglasny/bochner.git"
rev = "1b56973"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[lean_lib]]
name = "HilleYosida"
